# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lolesport < Formula
  desc "LoL Esports in your terminal"
  homepage ""
  version "0.0.0-dev.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matthieugusmini/lolesport/releases/download/v0.0.0-dev.1/lolesport_Darwin_x86_64.tar.gz"
      sha256 "f2177b33c638f52df1b38f6f9a611e87710d83345b8eefd435cf6ab779c6e3e7"

      def install
        bin.install "lolesport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matthieugusmini/lolesport/releases/download/v0.0.0-dev.1/lolesport_Darwin_arm64.tar.gz"
      sha256 "0bd67d3aced870643b3a96436483814908d40793d4ba778f9df2c4e3ede440f7"

      def install
        bin.install "lolesport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/matthieugusmini/lolesport/releases/download/v0.0.0-dev.1/lolesport_Linux_x86_64.tar.gz"
      sha256 "46f486d1933d0d511a163a5a4b2d74e38799b6693f98a4360b7895ac1d237338"
      def install
        bin.install "lolesport"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/matthieugusmini/lolesport/releases/download/v0.0.0-dev.1/lolesport_Linux_arm64.tar.gz"
      sha256 "542b2715cf7eac217f5e805ab51affbec0c5ce955e56f19e583840b49876fe7b"
      def install
        bin.install "lolesport"
      end
    end
  end
end
