# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lolesport < Formula
  desc "LoL Esports in your terminal"
  homepage ""
  version "0.0.0-dev.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matthieugusmini/lolesport/releases/download/v0.0.0-dev.1/lolesport_Darwin_x86_64.tar.gz"
      sha256 "8528c6d4482ea644dbade609f562d7ac7f33e0e30fe871e6457911d624f3b5cc"

      def install
        bin.install "lolesport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matthieugusmini/lolesport/releases/download/v0.0.0-dev.1/lolesport_Darwin_arm64.tar.gz"
      sha256 "d7621a08c1e0a83e3c97b021b2be8b4a7ad48288037445f82cb94256a05604e7"

      def install
        bin.install "lolesport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/matthieugusmini/lolesport/releases/download/v0.0.0-dev.1/lolesport_Linux_x86_64.tar.gz"
      sha256 "5bb61498c7f01fbd261e9c9b78e21e2d6a1f16d985eb73efceaa4d03eaa50c38"
      def install
        bin.install "lolesport"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/matthieugusmini/lolesport/releases/download/v0.0.0-dev.1/lolesport_Linux_arm64.tar.gz"
      sha256 "495a820a9824ea2aa33d6051f279f8b3f223589566e99734f342a29855469115"
      def install
        bin.install "lolesport"
      end
    end
  end
end
