# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rift < Formula
  desc "LoL Esports in your terminal"
  homepage "https://github.com/matthieugusmini/rift"
  version "0.1.1"
  license "mit"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Darwin_x86_64.tar.gz"
      sha256 "5b0277ab0306b272b2b2bcf9af596907023114ef3cd800c1534b5f6f4a9ef7c8"

      def install
        bin.install "rift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Darwin_arm64.tar.gz"
      sha256 "e406ae4df250bc3f0fe2c78be848fae728433616fc52f6dd2f2dc97479d44407"

      def install
        bin.install "rift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Linux_x86_64.tar.gz"
      sha256 "c4d03e35b800930109a1e595d3dcd0e4d9bed709c9e63eb660508c57d6ea1c2b"
      def install
        bin.install "rift"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Linux_arm64.tar.gz"
      sha256 "23e6c1c521138331fcd59dcf295b3eca6ad99104b4bc3915e54400d7b81f9804"
      def install
        bin.install "rift"
      end
    end
  end
end
