# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rift < Formula
  desc "LoL Esports in your terminal"
  homepage "https://github.com/matthieugusmini/rift"
  version "0.1.0"
  license "mit"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Darwin_x86_64.tar.gz"
      sha256 "d90cac8c5f23a35974ea3432de72251fb513ccaad3514b2f2b8cb5a2d4d85b23"

      def install
        bin.install "rift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Darwin_arm64.tar.gz"
      sha256 "7086c574d76e54840cdc47be214155053c82bdc3fbd1e9d6fc478e488ebe8406"

      def install
        bin.install "rift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Linux_x86_64.tar.gz"
      sha256 "ddcc40f0e05461acbe2d1535c44d2010a8db59cd38520beb563a11e081d8262c"
      def install
        bin.install "rift"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Linux_arm64.tar.gz"
      sha256 "6f120ab5c994bc816a476d62b0e42ecf1fb8b1e5eae38a5acdaf181313d71df2"
      def install
        bin.install "rift"
      end
    end
  end
end
